travis:
  secure:
    BINSTAR_TOKEN: wmPasXY3bzpWHSuk3T5iKCQynMfebOG+n0U4KD2heXZeZAWlYonvYo5xIeHnO7r7TbXzZ4mvZPq9nbld5UtZFR74OolqAlPKPofY+5hEetjtfnN0de0sbyknfcgJVSF2a1oc4mDNJElEcKqBevoJy3FJRYTv+6jI6i4x8ToMslQNe5akNw2wwPHIdtBtfWLverA86nE8/uMwmnxcyTO1ZzRnfX4Q2Trf4A/53mbQqudlnCssXEnsQbDttTtmU8FuuEn3ioEfN3zfzoSaNnvDZWDcDReBLyi2DJEFU8i8Mdul7syMhl2pSCxDmKYjOCz0RD0NctMT45DJ30Iufcll5qEJoCDKC/ex6wnTKsnjKM8M0maUsQZ7C9e6xYzAL2pRU+lnSPzDdW06GTlmvrHR8XhDSluqo/u/b7xyCNllAec2m1a8ZOXuZp6DsXzlsmtS3vGp2Fb0W+Wn9DonLLzKj9Uz68BDOKU+qi3nabR744VtwBeoHPNdpEZZrl94qKwlQZETTksTm+SjUrrX/i/6vyagYq58ucLFiYVl2cKZtAYbZCksrN8Aho3Gg29Y7tfXZ2KBmGHI7rntG6VKIafh6Jtl1DooNGDli0uNc9lImE0dzkNJSuRGYXEDvsYzzHu3by3hqQfTBcGbscqsS4jI82agtc2MCMJhECGirvKikGY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
